import type { NextPage } from "next";
import Head from "next/head";
import PostList from "../components/PostList";
import Section from "../components/Section";
import { Post } from "../utils/types/types";

interface PostsData {
  data?: { posts: Post[] };
}

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Tijani Fulani | Home</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.svg' />
      </Head>
      <Section title={"Home"}>
        <div className='mb-6'>
          <p>
            Hello, I am a software engineer from London, UK. Welcome to my
            little piece on the internet, where I write about programming and
            other such things.
          </p>
        </div>
      </Section>
      {/*<Section title="Latest Posts">*/}
      {/*    /!*<PostList posts={data.posts} limit={5} />*!/*/}
      {/*    <p>Blog Posts coming soon</p>*/}
      {/*</Section>*/}
    </div>
  );
};

export default Home;
